### PR TITLE
Edit delete user

### PR DESCRIPTION
**Pull request by zhangium**
I rebased off the advanced login because I realized I needed a lot of code from there. Feel free to disregard that pull request and just merge this one in.
- remember me option when logging in
- logged in users can edit their profile
- added a delete method for users but it's not hooked up to anything yet
- the Users page now displays all valid users

### CODE REVIEW

**Comment by zhangium** [comment]
[Edit/Delete Actions for Users, User Permissions to Pages](https://trello.com/c/CtZjnlVh/34-edit-delete-actions-for-users-user-permissions-to-pages)

**Comment by zhangium** [comment]
Fixed!

**Comment by ryan-mok** [comment]
There are a few more Rubocop violations using `"` when it should be `'`, but I can do these manually later when fixing all the Rubocop violations. If you have the chance, please fix them, but if not I can do them as part of another piece of work.

**Comment by zhangium** [comment]
Fixed most quotation violations, also added a .rubocop.yml file for now to decrease noise when running rubocop. We can remove it later if we find those style violations important enough.

**Pull request merged**
